version = 1

[install]
# Core build tools
gcc.pkg-path = "gcc"
autoconf.pkg-path = "autoconf"
automake.pkg-path = "automake"
libtool.pkg-path = "libtool"
pkgconfig.pkg-path = "pkg-config"
bash.pkg-path = "bash"
gnused.pkg-path = "gnused"
gnumake.pkg-path = "gnumake"
autoconf-archive.pkg-path = "autoconf-archive"
patch.pkg-path = "patch"
gum.pkg-path = "gum"

# Optional libraries for additional formats
file.pkg-path = "file"  # For libmagic
zlib.pkg-path = "zlib"
libpng.pkg-path = "libpng"
libid3tag.pkg-path = "libid3tag"
lame.pkg-path = "lame"
libmad.pkg-path = "libmad"
twolame.pkg-path = "twolame"
libsndfile.pkg-path = "libsndfile"
wavpack.pkg-path = "wavpack"
flac.pkg-path = "flac"
libvorbis.pkg-path = "libvorbis"


[vars]
SOX_ENABLE_OPTIONAL_FORMATS = "true"

[build]
sox-dsd.sandbox = "pure"
sox-dsd.command = '''
mkdir -p $out/bin
autoreconf -i
./configure --prefix=$out || exit 1
make -j$(nproc) || exit 1
make install
'''
