version = 1

[install]
# Core build tools
gcc.pkg-path = "gcc-unwrapped"
autoconf.pkg-path = "autoconf"
automake.pkg-path = "automake"
libtool.pkg-path = "libtool"
pkgconfig.pkg-path = "pkg-config"
bash.pkg-path = "bash"
gnused.pkg-path = "gnused"
gnumake.pkg-path = "gnumake"
autoconf-archive.pkg-path = "autoconf-archive"
patch.pkg-path = "patch"
gum.pkg-path = "gum"

# Optional libraries for additional formats
file.pkg-path = "file"  # For libmagic
file.pkg-group = "dev"
zlib.pkg-path = "zlib"
zlib.pkg-group = "dev"
libpng.pkg-path = "libpng"
libpng.pkg-group = "dev"
libid3tag.pkg-path = "libid3tag"
libid3tag.pkg-group = "dev"
lame.pkg-path = "lame"
lame.pkg-group = "dev"
libmad.pkg-path = "libmad"
libmad.pkg-group = "dev"
twolame.pkg-path = "twolame"
twolame.pkg-group = "dev"
libsndfile.pkg-path = "libsndfile"
libsndfile.pkg-group = "dev"
wavpack.pkg-path = "wavpack"
wavpack.pkg-group = "dev"
flac.pkg-path = "flac"
flac.pkg-group = "dev"
libvorbis.pkg-path = "libvorbis"
libvorbis.pkg-group = "dev"


[vars]
SOX_ENABLE_OPTIONAL_FORMATS = "true"

[build]
sox-dsd.sandbox = "pure"
sox-dsd.command = '''
mkdir -p $out/bin
./configure --prefix=$out || exit 1
make || exit 1
make install
'''
