## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
# Core build tools
gcc.pkg-path = "gcc"
autoconf.pkg-path = "autoconf"
automake.pkg-path = "automake"
libtool.pkg-path = "libtool"
pkgconfig.pkg-path = "pkg-config"
gnumake.pkg-path = "gnumake"
autoconf-archive.pkg-path = "autoconf-archive"
patch.pkg-path = "patch"
gum.pkg-path = "gum"

# Optional libraries for additional formats
file.pkg-path = "file"  # For libmagic
zlib.pkg-path = "zlib"
libpng.pkg-path = "libpng"
libid3tag.pkg-path = "libid3tag"
lame.pkg-path = "lame"
libmad.pkg-path = "libmad"
twolame.pkg-path = "twolame"
libsndfile.pkg-path = "libsndfile"
wavpack.pkg-path = "wavpack"
flac.pkg-path = "flac"
libvorbis.pkg-path = "libvorbis"

# Linux-specific packages
alsa-lib.pkg-path = "alsa-lib"
alsa-lib.systems = ["aarch64-linux", "x86_64-linux"]
pulseaudio.pkg-path = "pulseaudio"
pulseaudio.systems = ["aarch64-linux", "x86_64-linux"]


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
SOX_ENABLE_OPTIONAL_FORMATS = "true"


## Build Section -----------------------------------------------------
##  ... defines reproducible builds using Nix's deterministic system
## -------------------------------------------------------------------
[build]
sox-dsd.command = '''
# Create directory structure in $out
mkdir -p $out/bin

# (a) Run apply-patches.sh
./apply-patches.sh apply || exit 1

# (b) Run ./configure if apply-patches.sh exits successfully
./configure --prefix=$out || exit 1

# (c) Run make to build SoX
make || exit 1

# Install the built binary to $out
make install
'''


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = '''
'''


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
